In [132]:
# core feature of numpy is query relatted to arrays
import numpy as np

## Create & Read

#### 1D Array

In [133]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [134]:
type(arr1)

numpy.ndarray

In [135]:
arr1.shape

(5,)

In [216]:
arr1.dtype

dtype('int64')

In [137]:
# Which dimentional array
arr1.ndim

1

In [138]:
arr1.size

5

#### 2D Array

In [139]:
arr2 = np.array([[1, 4, 5], [6, 7, 8]])
arr2

array([[1, 4, 5],
       [6, 7, 8]])

In [140]:
arr2.ndim

2

In [141]:
arr2.shape # (row, colum)

(2, 3)

In [142]:
arr2.dtype

dtype('int64')

In [143]:
arr2.size

6

#### 3D Array

In [144]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [145]:
arr3.ndim

3

In [146]:
# (Represents the number of "layers" or "blocks" in the array,
# The horizontal arrangement within each layer,
# The vertical arrangement within each layer)
arr3.shape

(2, 2, 3)

In [147]:
# No. of elements in array
arr3.size

12

### Create random array

In [148]:
randomArr = np.random.rand(3, 2, 3)

In [149]:
randomArr

array([[[0.27995063, 0.96524897, 0.89423192],
        [0.45592342, 0.42664558, 0.12253636]],

       [[0.180709  , 0.77771246, 0.62175705],
        [0.20427699, 0.20340589, 0.53240064]],

       [[0.87782695, 0.98985078, 0.74835479],
        [0.066228  , 0.93136181, 0.6270163 ]]])

In [150]:
randomArr.dtype

dtype('float64')

In [151]:
zerosArr = np.zeros((3, 2, 3))
zerosArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [152]:
full = np.full((3, 2, 3), 5)
full

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [153]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [154]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [155]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
arr3[0][0]

array([1, 2, 3])

In [157]:
arr3[0][0][0]

np.int64(1)

In [158]:
arr3[0:2] # zero to two (0, 1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [159]:
arr3[-1] # last

array([[ 7,  8,  9],
       [10, 11, 12]])

In [160]:
# target perticular element
arr3[1][0][2] # second block, first row, third element

np.int64(9)

In [161]:
arr3[1, 0, 2]

np.int64(9)

### Update & delete

In [162]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [163]:
a1

array([[[0.85697465, 0.55841057],
        [0.37537211, 0.66043347],
        [0.28689994, 0.66379647]],

       [[0.71663777, 0.59941693],
        [0.23550497, 0.18492077],
        [0.52506493, 0.60456391]]])

In [164]:
a2

array([[[0.56980772, 0.53708354],
        [0.50818068, 0.16666172],
        [0.60355004, 0.93004068]],

       [[0.60063718, 0.76877602],
        [0.25346331, 0.47819336],
        [0.93665427, 0.01926579]]])

#### Basic math operations

In [165]:
np.add(a1, a2)

array([[[1.42678237, 1.09549411],
        [0.8835528 , 0.82709519],
        [0.89044998, 1.59383715]],

       [[1.31727495, 1.36819295],
        [0.48896828, 0.66311413],
        [1.46171919, 0.6238297 ]]])

In [166]:
np.subtract(a1, a2)

array([[[ 0.28716693,  0.02132703],
        [-0.13280857,  0.49377176],
        [-0.3166501 , -0.26624421]],

       [[ 0.1160006 , -0.16935909],
        [-0.01795835, -0.29327259],
        [-0.41158934,  0.58529812]]])

In [167]:
np.divide(a1, a2)

array([[[ 1.50397163,  1.03970896],
        [ 0.73865876,  3.96271855],
        [ 0.47535403,  0.71372842]],

       [[ 1.19312923,  0.77970295],
        [ 0.92914815,  0.3867071 ],
        [ 0.56057496, 31.38017287]]])

In [168]:
np.multiply(a1, a2)

array([[[0.48831077, 0.29991312],
        [0.19075686, 0.11006898],
        [0.17315847, 0.61735772]],

       [[0.43043929, 0.46081736],
        [0.05969187, 0.08842789],
        [0.4918043 , 0.0116474 ]]])

#### Stastical Operations

In [169]:
sqrt = np.sqrt(25)
abss = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [170]:
sqrt # squareroot of 25

np.float64(5.0)

In [171]:
abss # only positive integer or absolute value

np.int64(2)

In [172]:
power # 2 to the power of 8

np.int64(256)

In [173]:
log # log of 25

np.float64(3.2188758248682006)

In [174]:
mins # minimum or the lowest value from the array a1

np.float64(0.18492077086621383)

In [175]:
maxs # maimum or the biggest value from the array a2

np.float64(0.93665426535938)

#### Update

In [176]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [177]:
# firstly target the element and write the replace value
arr3[0, 0, 2] = 500
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [178]:
# from lowest value to biggest
arr3.sort()
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [179]:
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [180]:
arr3.shape

(2, 2, 3)

In [181]:
reshape_arr = arr3.reshape(2, 3, 2)
reshape_arr

array([[[  1,   2],
        [500,   4],
        [  5,   6]],

       [[  7,   8],
        [  9,  10],
        [ 11,  12]]])

#### Apending & inserting

In [183]:
zerosArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [189]:
onceArr = np.ones((3,2,3))
onceArr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [192]:
appd = np.append(zerosArr, onceArr, axis=0) # axis 0 is row & axis 1 is colum
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [193]:
# Insert

In [195]:
zerosArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [196]:
onceArr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [199]:
insert = np.insert(zerosArr, 1, onceArr, axis=0) 
# 1 represent the place where we have to insert array, 1 means we have to insert array after 0th block that means 1th block
insert

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [202]:
newArr = np.random.rand(3,2,3)
newArr

array([[[0.87003891, 0.87261837, 0.5264788 ],
        [0.43530174, 0.7667535 , 0.79850348]],

       [[0.07986093, 0.97813769, 0.82449492],
        [0.42571181, 0.72014539, 0.49833243]],

       [[0.25698265, 0.84637269, 0.34510365],
        [0.7125469 , 0.25128195, 0.85697315]]])

In [203]:
# delete the array

In [206]:
arrNew = np.delete(newArr, 0, axis=1) # 1st row of all block deleted
arrNew

array([[[0.43530174, 0.7667535 , 0.79850348]],

       [[0.42571181, 0.72014539, 0.49833243]],

       [[0.7125469 , 0.25128195, 0.85697315]]])

In [210]:
# Save array in seperate file
np.save('newArray', arrNew)

In [211]:
# load the file
np.load('newArray.npy')

array([[[0.43530174, 0.7667535 , 0.79850348]],

       [[0.42571181, 0.72014539, 0.49833243]],

       [[0.7125469 , 0.25128195, 0.85697315]]])